### ISSUE TITLE
Tattoo

### ISSUE THREAD

**Issue by benfoxall** [benfoxall/benfoxall.github.com#25]
Some kind of simple geometric shape - cubes?

~~Back of my right bicep~~ right tricep I think.

**Comment by benfoxall** [comment]
![photo on 14-06-2016 at 17 22](https://cloud.githubusercontent.com/assets/51385/16050878/3b9bbc52-3255-11e6-880d-dc29996c2100.jpg)

**Comment by Drarok** [comment]
Does sharpie count? 😜
