### ISSUE TITLE
Board Waxing

### ISSUE THREAD

**Issue by benfoxall** [benfoxall/benfoxall.github.com#38]
HEY @spikeheap! I need to wax my board.  I've got wax, but don't have an iron or scraper thing.  Do you have those?  Any chance I could borrow them?

**Comment by spikeheap** [comment]
Hey @benfoxall, I _love_ the fact you've got an `external` label and raised this as an issue! 

I have an iron, brush and scraper, and an edge file. You're more than welcome to borrow them, but I've got a workbench setup in my shed so how about you and Sarah could come over for dinner one evening, pick up the brakes and wax the board (is that scope creep? should I open a new issue?).

**Comment by benfoxall** [comment]
Yeah @spikeheap! I love the `external` label - opens it up to a whole lot more things.

**ACE.**

I don't think it's scope creep;  Dinner sounds like a really awesome way to resolve this - thanks for offering.  I've talked to Sarah - next week sometime would be good.  Does Tuesday work?

**Comment by spikeheap** [comment]
Sold @benfoxall. Expect a calendar invitation imminently.

**Comment by benfoxall** [comment]
email is hard.  Why can't everyone just use github issues?

**Comment by benfoxall** [comment]
@spikeheap! It's TODAY! Sarah said that Jen mentioned to her to tell me to ask you if you'd be interested in picking us up from town?

Would that be cool?  What time is good?  We'll be ready around 6.30-7 I think

**Comment by spikeheap** [comment]
@benfoxall it TOTALLY is. I'm pretty interested in picking you up. Where will you be? The train station is probably easiest for me (roadworks in town are a bit of a nightmare atm.), but I could swing round the back of Oxford if you'll be up by St Clements...

![awesome possom](http://media.giphy.com/media/f8GP12BMndCxy/giphy.gif)

**Comment by benfoxall** [comment]
ACE.  I'm glad you're interested! 

I've got to head back to St Clements to pick up my board - so could we meet there?

![giphy-1](https://cloud.githubusercontent.com/assets/51385/6710701/5eaf0c08-cd7a-11e4-973c-5fef8177239d.gif)

**Comment by omgmog** [comment]
> I need to wax my board

Is that a euphemism?

**Comment by benfoxall** [comment]
@omgmog nope!

[![10471991_818253338254926_2084364524_n](https://cloud.githubusercontent.com/assets/51385/6729188/b82b2476-ce27-11e4-94c6-fc17f7f3876e.jpg)](https://instagram.com/p/0YvOG0nPBC/)

Thanks a lot @spikeheap!  Yesterday was tonnes of fun.
