### ISSUE TITLE
Feedback on Firebug Websocket Monitor

### ISSUE THREAD

**Issue by benfoxall** [benfoxall/benfoxall.github.com#52]
Check out https://github.com/firebug/websocket-monitor and feedback to Alistair

things to look into:
- handling multiple connections
- filtering heartbeat events
- filtering by time - scroll back/pausing?
- individual timing
- export/replay
- online/offline feedback
- worker connections

**Comment by janodvarko** [comment]
Btw. here is Home page with feature list:
https://github.com/firebug/websocket-monitor/wiki

Honza

**Comment by janodvarko** [comment]
Also, one question is whether displaying a list of WS frames is actually the correct approach. We might want to display a list of WS messages where messages that span more frames are expandable -> to see all frames belonging to the message.
Thoughts?
Honza
